[versions]
kotlin = "2.0.20"
compose-multiplatform = "1.6.11"
detekt = "2.0.0-alpha.5"
detekt-formatting = "1.23.8"
coroutines = "1.8.1"
kotlinx-datetime = "0.6.0"
truth = "1.4.4"
javacv = "1.5.13"
javacpp = "1.5.13"
ffmpeg = "8.0.1-1.5.13"
ksp = "2.0.20-1.0.25"
kotlin-inject = "0.7.2"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt-formatting" }
javacv = { module = "org.bytedeco:javacv", version.ref = "javacv" }
ffmpeg = { module = "org.bytedeco:ffmpeg", version.ref = "ffmpeg" }
javacpp = { module = "org.bytedeco:javacpp", version.ref = "javacpp" }
kotlin-inject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime-kmp", version.ref = "kotlin-inject" }
kotlin-inject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlin-inject" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
