import java.io.ByteArrayOutputStream

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.ksp)
}

kotlin {
    jvm("desktop") {
        mainRun {
            mainClass = "dev.mj31.logger.client.app.MainKt"
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                api(project(":domain"))
                implementation(project(":data"))
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.components.resources)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.datetime)
                implementation(libs.kotlin.inject.runtime)
            }
        }

        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.kotlinx.coroutines.swing)
            }
        }

        val commonTest by getting {
            dependencies {
                implementation(libs.kotlin.test)
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.truth)
            }
        }

        val desktopTest by getting {
            dependencies {
                implementation(compose.desktop.uiTestJUnit4)
                implementation(compose.desktop.currentOs)
            }
        }
    }
}

/** Every user visible string lives in `composeResources`, so a translation is a new values folder. */
compose.resources {
    publicResClass = true
    packageOfResClass = "dev.mj31.logger.client.app.resources"
    generateResClass = auto
}

/** kotlin-inject generates the graph for the JVM target; the component itself stays in commonMain. */
dependencies {
    add("kspDesktop", libs.kotlin.inject.compiler)
}

/**
 * Writes the product version into a source file the About window can read.
 *
 * `gradle.properties` is the single place the version is defined, and a constant typed in by hand
 * beside it would be a second one, silently wrong from the first release that forgot it.
 */
val generateBuildInfo = tasks.register("generateBuildInfo") {
    description = "Generates the source file that carries the product version into the application."
    group = "build"

    val productVersion = project.version.toString()
    val outputDirectory = layout.buildDirectory.dir("generated/buildInfo/kotlin")
    inputs.property("productVersion", productVersion)
    outputs.dir(outputDirectory)

    doLast {
        val packageDirectory = outputDirectory.get().asFile.resolve("dev/mj31/logger/client/app")
        packageDirectory.mkdirs()
        packageDirectory.resolve("BuildInfo.kt").writeText(
            """
            package dev.mj31.logger.client.app

            /** Generated by the build from `gradle.properties`; edits here are overwritten. */
            object BuildInfo {

                const val PRODUCT_VERSION: String = "$productVersion"
            }

            """.trimIndent(),
        )
    }
}

kotlin.sourceSets.getByName("desktopMain").kotlin.srcDir(generateBuildInfo)

/**
 * Native installers accept a purely numeric version (`MAJOR[.MINOR][.PATCH]`, major greater than
 * zero) on every platform, so a pre-release qualifier cannot be stored in jpackage metadata at all.
 *
 * The product version keeps the qualifier; the installer carries its numeric core, which is the same
 * release it belongs to.
 */
fun installerVersion(version: String): String = version.substringBefore(delimiter = '-')

/** Name shared by the application bundle and by the installer artefact. */
val appPackageName = "MJLogs"

/**
 * Everything the application needs beside its own code at runtime, staged by jpackage into
 * `app/resources` and pointed at by `compose.application.resources.dir`.
 *
 * `common/` holds the licence texts every binary distribution has to carry, and `common/tessdata/`
 * the recognition model that reads the clock off a screencast. The two live under one root because
 * jpackage takes exactly one, and the root is named after that job rather than after either of its
 * tenants — it was called `legal` while the notices were the only thing in it.
 */
val appResourcesDirectory: Directory = layout.projectDirectory.dir("appResources")

/** Folder the disk image shows next to the application, so the notices need no bundle spelunking. */
val dmgLegalFolderName = "Licenses"

/** jpackage only ever builds the installer of the machine it runs on, so the host decides the rules. */
val isMacOsHost: Boolean = System.getProperty("os.name").lowercase().contains("mac")

/**
 * Stages the notices under the name the disk image should show.
 *
 * jpackage names the entry after the path it is given, so the folder cannot simply be
 * `appResources/common`.
 *
 * Only the texts are taken. The same folder also carries the recognition model, and a multi-megabyte
 * binary sitting in a folder labelled `Licenses` would be a puzzle rather than a notice.
 */
val stageDmgLegalNotices = tasks.register<Sync>("stageDmgLegalNotices") {
    description = "Collects the licence texts that the disk image shows next to the application."
    group = "distribution"

    from(appResourcesDirectory.dir("common")) { include("*.txt") }
    into(layout.buildDirectory.dir("legal/$dmgLegalFolderName"))
}

/**
 * Puts the notices in the root of the disk image.
 *
 * jpackage only ever writes them inside the application bundle, and macOS shows a bundle as a single
 * opaque file: without this the only way to reach the licences is "Show Package Contents", which is
 * not the "prominent notice" the LGPL asks for. `--mac-dmg-content` arrived in JDK 21, so an older
 * toolchain keeps building, it just produces a disk image with nothing beside the application.
 *
 */
tasks.withType<org.jetbrains.compose.desktop.application.tasks.AbstractJPackageTask>()
    .matching { it.name == "packageDmg" || it.name == "packageReleaseDmg" }
    .configureEach {
        if (JavaVersion.current() < JavaVersion.VERSION_21) {
            logger.warn(
                "jpackage ${JavaVersion.current()} has no --mac-dmg-content: the licence texts will " +
                    "only be inside $appPackageName.app, not next to it in the disk image.",
            )
            return@configureEach
        }

        dependsOn(stageDmgLegalNotices)
        val stagedNotices = layout.buildDirectory.dir("legal/$dmgLegalFolderName")
        freeArgs.addAll(
            provider { listOf("--mac-dmg-content", "\"${stagedNotices.get().asFile.absolutePath}\"") },
        )
    }

/**
 * Everything that decides how the disk image looks, drawn outside the build and committed.
 *
 * `background@2x.png` is the artwork; `dmg-setup.scpt` is the AppleScript that arranges the window
 * over it. The two share one grid, written down in `dmg/README.md`, because Finder never scales a
 * background picture: a drawing that does not match the window it sits behind cannot be nudged into
 * place afterwards, it is simply wrong by however many points it is off.
 */
val dmgDesignDirectory: Directory = layout.projectDirectory.dir("dmg")

/** Size of the disk image window in points, and therefore of the artwork at @1x. */
val dmgWindowWidth = 660
val dmgWindowHeight = 440

val dmgResourcesDirectory: Provider<Directory> = layout.buildDirectory.dir("dmg/resources")
val dmgBackgroundFile: Provider<RegularFile> =
    layout.buildDirectory.file("dmg/background/$appPackageName-background.tiff")

/** The script the shell tools live in; `sips` and `tiffutil` have no Gradle equivalent. */
val backgroundScript: RegularFile = rootProject.layout.projectDirectory.file("scripts/make-dmg-background.sh")

/**
 * Turns the artwork into the picture Finder can actually show.
 *
 * A Retina display needs the background at twice the size, and one TIFF carries both
 * representations — which is why the committed asset is a PNG and the staged one is not.
 */
val buildDmgBackground = tasks.register<Exec>("buildDmgBackground") {
    description = "Converts the disk image artwork into the two-resolution TIFF that Finder shows."
    group = "distribution"
    onlyIf { isMacOsHost }

    // A file collection rather than `inputs.file`, which fails on a missing input before the task
    // runs and would replace the script's explanation with Gradle's.
    val artwork = dmgDesignDirectory.file("background@2x.png")
    inputs.files(artwork)
    inputs.file(backgroundScript)
    outputs.file(dmgBackgroundFile)

    executable = backgroundScript.asFile.absolutePath
    argumentProviders.add(
        CommandLineArgumentProvider {
            listOf(
                artwork.asFile.absolutePath,
                dmgBackgroundFile.get().asFile.absolutePath,
                dmgWindowWidth.toString(),
                dmgWindowHeight.toString(),
            )
        },
    )
}

/**
 * The three files jpackage reads to decide how the disk image looks, under the names it looks for.
 *
 * jpackage finds a resource by `<package name>-<role>`, falls back to its own template for anything
 * missing, and says which of the two it used at `--verbose`. The volume icon is the application icon:
 * a mounted disk that carries the drawing of the thing inside it needs no label.
 */
val stageDmgResources = tasks.register<Sync>("stageDmgResources") {
    description = "Collects the artwork, the window script and the volume icon for jpackage."
    group = "distribution"
    onlyIf { isMacOsHost }

    from(buildDmgBackground)
    from(dmgDesignDirectory.file("dmg-setup.scpt")) { rename { "$appPackageName-dmg-setup.scpt" } }
    from(project.file("icons/icon.icns")) { rename { "$appPackageName-volume.icns" } }
    into(dmgResourcesDirectory)
}

/**
 * Builds the disk image by calling jpackage directly, which is the only way to style it at all.
 *
 * Compose runs jpackage itself for `packageDmg`, and passes `--resource-dir` pointing at a directory
 * it wipes inside its own task action — so the overrides above cannot be put there. `freeArgs` are no
 * way round it either: Compose emits them *before* its own arguments, and of two `--resource-dir`
 * options jpackage keeps the last. Both halves of that were checked against jpackage 21 rather than
 * assumed. What is left is to run the tool ourselves, over the application bundle Compose has already
 * built, and hand it the directory we want.
 *
 * `packageDmg` still works and still carries the notices; it is simply not what a release ships.
 */
val packageStyledDmg = tasks.register<Exec>("packageStyledDmg") {
    description = "Builds the styled macOS disk image from the application bundle."
    group = "distribution"
    onlyIf { isMacOsHost }

    val appImageDirectory = tasks
        .named<org.jetbrains.compose.desktop.application.tasks.AbstractJPackageTask>("createDistributable")
        .flatMap { it.destinationDir }
    val stagedNotices = layout.buildDirectory.dir("legal/$dmgLegalFolderName")
    val imageDirectory = layout.buildDirectory.dir("dmg/image")

    dependsOn(stageDmgResources, stageDmgLegalNotices)
    inputs.dir(appImageDirectory)
    inputs.dir(dmgResourcesDirectory)
    inputs.dir(stagedNotices)
    outputs.dir(imageDirectory)

    executable = File(System.getProperty("java.home"), "bin/jpackage").absolutePath
    argumentProviders.add(
        CommandLineArgumentProvider {
            listOf(
                "--type", "dmg",
                "--name", appPackageName,
                "--app-version", installerVersion(version = project.version.toString()),
                "--app-image", appImageDirectory.get().asFile.resolve("$appPackageName.app").absolutePath,
                "--resource-dir", dmgResourcesDirectory.get().asFile.absolutePath,
                "--mac-dmg-content", stagedNotices.get().asFile.absolutePath,
                "--dest", imageDirectory.get().asFile.absolutePath,
                "--verbose",
            )
        },
    )

    // Everything jpackage says is kept and only shown when something is wrong: `--verbose` is on
    // because the log is the only place the layout step reports itself, and it is several hundred
    // lines of hdiutil noise otherwise.
    val log = ByteArrayOutputStream()
    standardOutput = log
    errorOutput = log
    isIgnoreExitValue = true

    // jpackage refuses to overwrite an image it built before, and leaves the stale one behind.
    doFirst { imageDirectory.get().asFile.deleteRecursively() }

    doLast {
        val output = log.toString()
        val failed = executionResult.get().exitValue != 0

        // An unauthorised layout script does not stop jpackage: it writes a perfectly valid disk
        // image with the icons where Finder happened to drop them, and exits zero. That is worse
        // than a failure, because the only symptom is an installer that looks wrong.
        val layoutRefused = output.contains("execution error") || output.contains("-1743")

        if (failed || layoutRefused) {
            logger.error(output)
        }
        if (!failed && layoutRefused) {
            throw GradleException(
                "The disk image was built but not arranged: macOS refused the layout script " +
                    "permission to control Finder. Grant it under System Settings > Privacy & " +
                    "Security > Automation for the program that started this build, then run again.",
            )
        }
        if (failed) {
            throw GradleException("jpackage failed to build the disk image; its output is above.")
        }
    }
}

/** Must match `SessionFile.EXTENSION`; the build cannot read a Kotlin constant it is compiling. */
val sessionExtension = "mjclog"
val sessionTypeName = "MJLogs session"

/**
 * Teaches the operating system that the session extension belongs to this application.
 *
 * jpackage takes one properties file per association and no list, so the file is generated rather
 * than committed: its content is the extension plus a description, both of which already exist in
 * the code that defines the format.
 *
 * The directory is emptied first. It is an output that is written into rather than replaced, so
 * without this the descriptors of extensions that no longer exist keep being handed to jpackage —
 * which is exactly what happened when the two older formats were dropped.
 *
 * This only ever affects an *installed* application. Running from Gradle leaves no registration
 * behind, so double-clicking a session file is the one thing that cannot be checked before building
 * an installer.
 */
val sessionFileAssociations = tasks.register("generateSessionFileAssociations") {
    description = "Writes the jpackage descriptor that associates the session extension."
    group = "distribution"

    val outputDirectory = layout.buildDirectory.dir("associations")
    outputs.dir(outputDirectory)

    doLast {
        val directory = outputDirectory.get().asFile
        directory.deleteRecursively()
        directory.mkdirs()
        listOf(
            sessionExtension to sessionTypeName,
        ).forEach { (extension, description) ->
            directory.resolve("$extension.properties").writeText(
                """
                extension=$extension
                mime-type=application/x-$extension
                description=$description
                """.trimIndent(),
            )
        }
    }
}

/**
 * Windows and Linux only, and that is not an oversight.
 *
 * There, jpackage builds the package itself and honours `--file-associations`. On macOS it does not:
 * Compose produces the `.app` in a separate app-image step, and jpackage writes
 * `CFBundleDocumentTypes` only when it is building an installer from scratch — so the option is
 * accepted, ignored, and the bundle ships without a single document type. That was checked by
 * reading the generated `Info.plist`, not assumed. macOS is handled below, in the plist itself.
 */
if (!isMacOsHost) {
    tasks.withType<org.jetbrains.compose.desktop.application.tasks.AbstractJPackageTask>().configureEach {
        dependsOn(sessionFileAssociations)
        val associations = layout.buildDirectory.dir("associations")
        freeArgs.addAll(
            provider {
                associations.get().asFile
                    .listFiles { file -> file.extension == "properties" }
                    .orEmpty()
                    .sortedBy { it.name }
                    .flatMap { listOf("--file-associations", it.absolutePath) }
            },
        )
    }
}

/**
 * The document type macOS actually reads, written straight into the bundle.
 *
 * `LSHandlerRank = Owner` says this application defines the format rather than merely being able to
 * open it, which is what makes it the default handler instead of a candidate among several.
 *
 * Registration still needs the application to sit somewhere LaunchServices scans and to have been
 * launched once: mounting the disk image is not enough, and neither is copying without opening.
 */
val macDocumentTypes = """
    <key>CFBundleDocumentTypes</key>
    <array>
      <dict>
        <key>CFBundleTypeName</key>
        <string>$sessionTypeName</string>
        <key>CFBundleTypeExtensions</key>
        <array>
          <string>$sessionExtension</string>
        </array>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>LSHandlerRank</key>
        <string>Owner</string>
        <key>CFBundleTypeIconFile</key>
        <string>$appPackageName.icns</string>
      </dict>
    </array>
""".trimIndent()

/**
 * Publishes the installer under the full product version.
 *
 * jpackage can only name its output after the numeric version it accepts, so two pre-releases of the
 * same release would produce the very same file name. The bundle metadata stays untouched: the copy
 * only restores the qualifier in the artefact humans hand around.
 */
tasks.register<Copy>("dmg") {
    description = "Builds the macOS installer and names it after the full product version."
    group = "distribution"
    dependsOn(packageStyledDmg)

    val installerName = "$appPackageName-${project.version}.dmg"
    from(layout.buildDirectory.dir("dmg/image")) {
        include("*.dmg")
        rename { installerName }
    }
    into(layout.buildDirectory.dir("distributions"))

    doLast { logger.lifecycle("The installer is written to ${destinationDir.resolve(installerName)}") }
}

compose.desktop {
    application {
        mainClass = "dev.mj31.logger.client.app.MainKt"
        nativeDistributions {
            targetFormats(
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Dmg,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Msi,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Deb,
            )
            packageName = appPackageName
            packageVersion = installerVersion(version = project.version.toString())

            // jpackage links a minimal runtime; JavaCPP, and therefore the bundled FFmpeg decoder,
            // needs sun.misc.Unsafe from jdk.unsupported. Without it the packaged app starts but
            // cannot decode a single frame.
            modules("jdk.unsupported")

            // LGPL requires the licence to travel with the binaries it covers. The contents of
            // `common/` end up under `app/resources` inside the installed application: the texts are
            // read back by the Help menu, the model by the automatic synchronization.
            appResourcesRootDir.set(appResourcesDirectory)

            // The licence the MSI and DEB installers show and record for the product itself.
            //
            // Not on macOS: there jpackage would turn it into a click-through agreement on the disk
            // image, which then no longer mounts without a human at the keyboard, and an Apache 2.0
            // grant is not something a user has to accept before copying a file. The macOS copy
            // travels in the visible `Licenses` folder instead.
            if (!isMacOsHost) {
                licenseFile.set(appResourcesDirectory.file("common/LICENSE.txt"))
            }

            // The same drawing in the three containers the platforms insist on.
            macOS {
                bundleID = "dev.mj31.logger.client"
                iconFile.set(project.file("icons/icon.icns"))
                infoPlist {
                    extraKeysRawXml = macDocumentTypes
                }
            }

            windows {
                iconFile.set(project.file("icons/icon.ico"))
            }

            linux {
                iconFile.set(project.file("icons/icon.png"))
            }
        }
    }
}
