plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.ksp)
}

kotlin {
    jvm("desktop") {
        mainRun {
            mainClass = "dev.mj31.logger.client.app.MainKt"
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                api(project(":domain"))
                implementation(project(":data"))
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.components.resources)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.datetime)
                implementation(libs.kotlin.inject.runtime)
            }
        }

        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.kotlinx.coroutines.swing)
            }
        }

        val commonTest by getting {
            dependencies {
                implementation(libs.kotlin.test)
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.truth)
            }
        }

        val desktopTest by getting {
            dependencies {
                implementation(compose.desktop.uiTestJUnit4)
                implementation(compose.desktop.currentOs)
            }
        }
    }
}

/** Every user visible string lives in `composeResources`, so a translation is a new values folder. */
compose.resources {
    publicResClass = true
    packageOfResClass = "dev.mj31.logger.client.app.resources"
    generateResClass = auto
}

/** kotlin-inject generates the graph for the JVM target; the component itself stays in commonMain. */
dependencies {
    add("kspDesktop", libs.kotlin.inject.compiler)
}

/**
 * Writes the product version into a source file the About window can read.
 *
 * `gradle.properties` is the single place the version is defined, and a constant typed in by hand
 * beside it would be a second one, silently wrong from the first release that forgot it.
 */
val generateBuildInfo = tasks.register("generateBuildInfo") {
    description = "Generates the source file that carries the product version into the application."
    group = "build"

    val productVersion = project.version.toString()
    val outputDirectory = layout.buildDirectory.dir("generated/buildInfo/kotlin")
    inputs.property("productVersion", productVersion)
    outputs.dir(outputDirectory)

    doLast {
        val packageDirectory = outputDirectory.get().asFile.resolve("dev/mj31/logger/client/app")
        packageDirectory.mkdirs()
        packageDirectory.resolve("BuildInfo.kt").writeText(
            """
            package dev.mj31.logger.client.app

            /** Generated by the build from `gradle.properties`; edits here are overwritten. */
            object BuildInfo {

                const val PRODUCT_VERSION: String = "$productVersion"
            }

            """.trimIndent(),
        )
    }
}

kotlin.sourceSets.getByName("desktopMain").kotlin.srcDir(generateBuildInfo)

/**
 * Native installers accept a purely numeric version (`MAJOR[.MINOR][.PATCH]`, major greater than
 * zero) on every platform, so a pre-release qualifier cannot be stored in jpackage metadata at all.
 *
 * The product version keeps the qualifier; the installer carries its numeric core, which is the same
 * release it belongs to.
 */
fun installerVersion(version: String): String = version.substringBefore(delimiter = '-')

/** Name shared by the application bundle and by the installer artefact. */
val appPackageName = "MJLogs"

/**
 * Everything the application needs beside its own code at runtime, staged by jpackage into
 * `app/resources` and pointed at by `compose.application.resources.dir`.
 *
 * `common/` holds the licence texts every binary distribution has to carry, and `common/tessdata/`
 * the recognition model that reads the clock off a screencast. The two live under one root because
 * jpackage takes exactly one, and the root is named after that job rather than after either of its
 * tenants — it was called `legal` while the notices were the only thing in it.
 */
val appResourcesDirectory: Directory = layout.projectDirectory.dir("appResources")

/** Folder the disk image shows next to the application, so the notices need no bundle spelunking. */
val dmgLegalFolderName = "Licenses"

/** jpackage only ever builds the installer of the machine it runs on, so the host decides the rules. */
val isMacOsHost: Boolean = System.getProperty("os.name").lowercase().contains("mac")

/**
 * Stages the notices under the name the disk image should show.
 *
 * jpackage names the entry after the path it is given, so the folder cannot simply be
 * `appResources/common`.
 *
 * Only the texts are taken. The same folder also carries the recognition model, and a multi-megabyte
 * binary sitting in a folder labelled `Licenses` would be a puzzle rather than a notice.
 */
val stageDmgLegalNotices = tasks.register<Sync>("stageDmgLegalNotices") {
    description = "Collects the licence texts that the disk image shows next to the application."
    group = "distribution"

    from(appResourcesDirectory.dir("common")) { include("*.txt") }
    into(layout.buildDirectory.dir("legal/$dmgLegalFolderName"))
}

/**
 * Puts the notices in the root of the disk image.
 *
 * jpackage only ever writes them inside the application bundle, and macOS shows a bundle as a single
 * opaque file: without this the only way to reach the licences is "Show Package Contents", which is
 * not the "prominent notice" the LGPL asks for. `--mac-dmg-content` arrived in JDK 21, so an older
 * toolchain keeps building, it just produces a disk image with nothing beside the application.
 *
 */
tasks.withType<org.jetbrains.compose.desktop.application.tasks.AbstractJPackageTask>()
    .matching { it.name == "packageDmg" || it.name == "packageReleaseDmg" }
    .configureEach {
        if (JavaVersion.current() < JavaVersion.VERSION_21) {
            logger.warn(
                "jpackage ${JavaVersion.current()} has no --mac-dmg-content: the licence texts will " +
                    "only be inside $appPackageName.app, not next to it in the disk image.",
            )
            return@configureEach
        }

        dependsOn(stageDmgLegalNotices)
        val stagedNotices = layout.buildDirectory.dir("legal/$dmgLegalFolderName")
        freeArgs.addAll(
            provider { listOf("--mac-dmg-content", "\"${stagedNotices.get().asFile.absolutePath}\"") },
        )
    }

/**
 * Publishes the installer under the full product version.
 *
 * jpackage can only name its output after the numeric version it accepts, so two pre-releases of the
 * same release would produce the very same file name. The bundle metadata stays untouched: the copy
 * only restores the qualifier in the artefact humans hand around.
 */
tasks.register<Copy>("dmg") {
    description = "Builds the macOS installer and names it after the full product version."
    group = "distribution"
    dependsOn("packageDmg")

    val installerName = "$appPackageName-${project.version}.dmg"
    from(layout.buildDirectory.dir("compose/binaries/main/dmg")) {
        include("*.dmg")
        rename { installerName }
    }
    into(layout.buildDirectory.dir("distributions"))

    doLast { logger.lifecycle("The installer is written to ${destinationDir.resolve(installerName)}") }
}

compose.desktop {
    application {
        mainClass = "dev.mj31.logger.client.app.MainKt"
        nativeDistributions {
            targetFormats(
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Dmg,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Msi,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Deb,
            )
            packageName = appPackageName
            packageVersion = installerVersion(version = project.version.toString())

            // jpackage links a minimal runtime; JavaCPP, and therefore the bundled FFmpeg decoder,
            // needs sun.misc.Unsafe from jdk.unsupported. Without it the packaged app starts but
            // cannot decode a single frame.
            modules("jdk.unsupported")

            // LGPL requires the licence to travel with the binaries it covers. The contents of
            // `common/` end up under `app/resources` inside the installed application: the texts are
            // read back by the Help menu, the model by the automatic synchronization.
            appResourcesRootDir.set(appResourcesDirectory)

            // The licence the MSI and DEB installers show and record for the product itself.
            //
            // Not on macOS: there jpackage would turn it into a click-through agreement on the disk
            // image, which then no longer mounts without a human at the keyboard, and an Apache 2.0
            // grant is not something a user has to accept before copying a file. The macOS copy
            // travels in the visible `Licenses` folder instead.
            if (!isMacOsHost) {
                licenseFile.set(appResourcesDirectory.file("common/LICENSE.txt"))
            }

            // The same drawing in the three containers the platforms insist on.
            macOS {
                bundleID = "dev.mj31.logger.client"
                iconFile.set(project.file("icons/icon.icns"))
            }

            windows {
                iconFile.set(project.file("icons/icon.ico"))
            }

            linux {
                iconFile.set(project.file("icons/icon.png"))
            }
        }
    }
}
